### ISSUE TITLE
ibot.patched2 not being created

### ISSUE THREAD

**Issue by guai** [palera1n/ibootpatch2#1]
Hi
I was trying to jb my iphone 7 on ios 15.1 with palera1n
And I'm getting `sed: can't read ibot.patched2: No such file or directory` error
As long as I can see this file should be created at this line `"$dir"/iBootpatch2 --t8015 ibot.patched ibot.patched2`
but the file is not being created
I tried to call it myself:
```
root@prodesk:/home/guai/palera1n/work# ../binaries/Linux/iBootpatch2 --t8015 ibot.patched ibot.patched2
000000018001c000[0000000000000300]: iboot_base
root@prodesk:/home/guai/palera1n/work# ls
BuildManifest.plist  iBoot.d21.RELEASE.im4p  ibot.dec  ibot.patched
root@prodesk:/home/guai/palera1n/work# 
```
[Here](https://github.com/palera1n/ibootpatch2/files/10253496/ibot.patched.zip) is my `ibot.patched` file

**Comment by kaal18** [comment]
I'm facing the same issue.

**Comment by broskicoldi** [comment]
@kaal18 not only you , many are

you need to wait for the devs to fix it , something got borked

**Comment by plooshi** [comment]
#2 should fix this
